apiVersion: v2
name: tito-pizzeria
type: application
version: 0.1.0

dependencies:
  - name: ms-gateway
    version: 0.1.0
    repository: "file://charts/ms-gateway"
  - name: ms-productos
    version: 0.1.0
    repository: "file://charts/ms-productos"
  - name: ms-usuarios
    version: 0.1.0
    repository: "file://charts/ms-usuarios"
  - name: infra-nats
    version: 0.1.0
    repository: "file://charts/infra-nats"