{{- if .Values.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tito-ms-gateway-deployment
  namespace: {{ .Release.Namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tito-ms-gateway
  template:
    metadata:
      labels:
        app: tito-ms-gateway
    spec:
      containers:
        # 👇 AQUÍ: Cambiamos el include por el nombre estático
        - name: tito-ms-gateway
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          env:
            - name: PORT
              valueFrom:
                configMapKeyRef:
                  # 👇 AQUÍ: Cambiamos el include
                  name: tito-ms-gateway-config
                  key: PORT
            - name: NATS_SERVERS
              valueFrom:
                configMapKeyRef:
                  # 👇 AQUÍ: Cambiamos el include
                  name: tito-ms-gateway-config
                  key: NATS_SERVERS
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: jwt-token-secret
                  key: JWT_SECRET
          ports:
            - containerPort: {{ .Values.app.containerPort }}
          envFrom:
            - configMapRef:
                name: tito-ms-gateway-config
{{- end }}