{{- if .Values.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tito-ms-usuarios-deployment
  namespace: {{ .Release.Namespace }}
spec:
  replicas: {{ .Values.app.container.replicas }}
  selector:
    matchLabels:
      app: tito-ms-usuarios
  template:
    metadata:
      labels:
        app: tito-ms-usuarios
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
        checksum/secret: {{ include (print $.Template.BasePath "/secret-postgres.yaml") . | sha256sum }}
    spec:
      containers:
        - name: tito-ms-usuarios
          image: "{{ .Values.app.image.repository }}:{{ .Values.app.image.tag }}"
          imagePullPolicy: {{ .Values.app.image.pullPolicy | default "Always" }}
          ports:
            - containerPort: {{ .Values.app.containerPort }}
          resources:
            requests:
              memory: "512Mi"
              cpu: "250m"
            limits:
              memory: "1Gi"
              cpu: "1000m"
          env:
            - name: MICROSERVICIO
              value: "ms-usuarios"
            # Mantenemos DATABASE_URL porque usa la interpolación del password que viene del ConfigMap
            - name: DATABASE_URL
              value: "postgresql://{{ .Values.postgres.auth.username }}:$(DATABASE_PASSWORD)@{{ .Values.postgres.name }}:5432/{{ .Values.postgres.auth.database }}?schema=public"
            # 👇 BLOQUE ELIMINADO PARA EVITAR EL ERROR DE ARGO CD 👇
          envFrom:
            - configMapRef:
                name: tito-ms-usuarios-config
          volumeMounts:
            - name: ssh-key-volume
              mountPath: "/mnt/ssh-keys"
              readOnly: true
{{- end }}