enabled: true

app:
  image:
    repository: "jose196/tito-ms-usuarios"   # ← imagen propia del servicio
    tag: "latest"                              # Jenkins sobreescribirá este valor
    pullPolicy: Always
  containerPort: 3000
  container:
    name: tito-ms-usuarios
    replicas: 1

service:
  type: ClusterIP
  port: 3000

postgres:
  name: tito-ms-usuarios-postgres
  image:
    repository: postgres
    tag: "15-alpine"
    pullPolicy: IfNotPresent
  service:
    port: 5432
  auth:
    database: bdusuarios
    username: admin
    password: admin
  persistence:
    enabled: true
    size: 2Gi
    storageClassName: "microk8s-hostpath"

env:
  NODE_ENV: "production"
  DATABASE_HOST: "tito-ms-usuarios-postgres"
  DATABASE_PORT: "5432"
  DATABASE_NAME: "bdusuarios"
  DATABASE_USER: "admin"

global:
  env:
    REPO_GIT: "git@github.com:Rodriguez-22/backend-mc-pnpm.git"
    PORT: "3000"
  nats:
    url: "nats://nats.nats-system.svc.cluster.local:4222"